// <auto-generated />
namespace SIS_ITELEC3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeFkToSubjectsInGrades : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeFkToSubjectsInGrades));
        
        string IMigrationMetadata.Id
        {
            get { return "202405160615402_changeFkToSubjectsInGrades"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
